nodeLinker: node-modules
enableGlobalCache: true
enableOfflineMode: false
enableTelemetry: false
enableColors: true
enableConstraintsChecks: true
enableHardenedMode: true
nmHoistingLimits: "none"
nmMode: "hardlinks-global"
preferInteractive: true
preferReuse: true
